src/main/augurNodeController.js
=> Nicely formatted config files are crucial

README.md
People are gonna be downloading stuff from this repo, might as well make it purty
=> Polished up the README a bit

.travis.yml, scripts/build.sh
added setting to run build scripts on master (but only releases on a tag)
build command moved to script so we can conditionally install based on OS
=> moved build command to script, will run on master, release on tag

.travis.yml, scripts/build.sh
move npm install into build script so we can install deps first
=> move npm commands into build.sh

.travis.yml, scripts/preinstall.sh
fixes build dependencies, we still have the build terminating, but with an exit 0
=> Travis fixes

package-lock.json, package.json, src/main/augurNodeController.js
- Update to newest Augur packages
- Stop the processQueue then on a fresh start clear it out and resume. This fixes hot switch issues
- Store DB persistently and based on the network id so two different AN configurations that point to Rinkeby will still have the same storage
=> update, fix hot switching again, retain DB on a netid basis

src/main/augurNodeServer.js
[CH Issue](https://app.clubhouse.io/augur/story/12859/add-ssl-to-augur-app)
=> Changing Rinkeby setttings to use SSL

src/main/augurNodeServer.js
/cc @petong the other PR for the electron fix
=> Pass app data dir to augur node controller

package.json, src/renderer/index.html, src/renderer/renderer.js
These are complaints Webstorm had with the code.
=> Fix code inspection errors

src/main/main.js
=> add copy paste for mac

README.md
add section for creating self signed certs for mac.
=> document creating certs for mac to support ledger

package.json, src/main/augurNodeServer.js
=> update AN controller

src/main/augurNodeServer.js
=> add infura's augur http endpoint for mainnet

README.md
https://app.clubhouse.io/augur/story/13521/add-blurb-to-augur-app-about-config-json-doesnt-get-overrideen-by-installer
=> add gotcha with mainnet not in network configuration dropdown

src/renderer/renderer.js
https://app.clubhouse.io/augur/story/13534/augur-app-at-99-sync-for-a-long-time
=> activate button at 99%

src/renderer/index.html, src/renderer/renderer.js, src/renderer/styles.css
https://app.clubhouse.io/augur/story/13639/augur-app-blocks-remaining-shows-while-bulk-logs-are-downloaded-users-think-it-s-broken-not-working
=> add spinner to indicate we are doing stuff and the user needs to wait

src/renderer/renderer.js
=> remaining number is blank when 0 blocks remain

src/renderer/index.html
https://app.clubhouse.io/augur/story/13795/hide-reset-button-in-augur-app
=> hide reset button, having issues with augur-node resetDatabase method

src/main/augurNodeServer.js, src/renderer/renderer.js
This PR relies on https://github.com/AugurProject/augur-node/pull/535
https://app.clubhouse.io/augur/story/13794/augur-node-logging-logs-empty-messages
=> remove blank line logging a lot, clear logs to only have one logger

scripts/electron-build.sh, scripts/post_build.py
output sha in CI for debgging/verification
=> delete asset if it exists for that release. 

src/main/augurNodeServer.js, src/renderer/renderer.js
it might take a while to download the bulk data to process it. Give the user a message
https://app.clubhouse.io/augur/story/14185/add-message-to-users-logs-are-being-downloaded
=> give more detailed message that goes along with ... wait indicator

README.md
document how users can change the UI port in augur-app
=> updated readme to describe how users can change the ui port in augur-app

src/main/augurNodeServer.js, src/main/augurUIServer.js, src/renderer/renderer.js
@bthaile Before merging this, can you verify that the SSL Ledger stuff still works with this change?
=> Updated localhost -> 127.0.0.1

src/main/augurNodeServer.js, src/main/augurUIServer.js, src/renderer/renderer.js
https://app.clubhouse.io/augur/story/14448/redirect-http-to-https-when-ssl-is-enabled
add configurable ssl port with adding http redirect to https.
=> add redirect of http to https when ssl enabled

src/main/augurNodeServer.js
https://app.clubhouse.io/augur/story/14634/remove-infura-endpoints-from-augur-app
=> Remove infura endpoints

package-lock.json, package.json, src/main/augurNodeServer.js
- Display information for the user when reconnecting to ethereum node [augur-node doesn't inform augur-app connection with ethereum node was lost
](https://app.clubhouse.io/augur/story/14165/augur-node-doesn-t-inform-augur-app-connection-with-ethereum-node-was-lost)
- Reconnect on failures [Auto-restart Augur Node on failure](https://app.clubhouse.io/augur/story/13931/auto-restart-augur-node-on-failure)
- Restart bulk sync when too far behind [Github: Standby/Sleep Support](https://app.clubhouse.io/augur/story/14204/github-standby-sleep-support)
=> reconnect improvements

src/main/augurNodeServer.js
We don't want to try and restart to bulk sync when bulk syncing.
=> only restart to bulk sync when not already bulk syncing

README.md
Let's help the next person avoid this gotcha.
=> Warn against using Parity in light mode

package-lock.json, package.json, src/update/check-for-updates.js
There is an exception when running from a .deb archive. It would
seem the electron people want us to use the mechanics of the deb
distribution format/pipeline/smoke signal chorus
=> Wrap updater call in try/catch

package-lock.json, package.json
Author:    Augur Team <team@augur.net>
=> augur.js@5.4.0

.travis.yml, package-lock.json, package.json, scripts/create_release.sh
This brings master to new snapshot build, bringing in the changes from the 1.4.0 release
=> Version bump 1.5.0 snapshot

src/renderer/common/components/modal/components/modal-download-geth/modal-download-geth.js, src/renderer/common/components/modal/components/modal-download-geth/modal-download-geth.styles.less
=> change wording for download modal

src/renderer/app/components/processing-view/processing-view.js
=> change where rounding is done

src/renderer/app/App.js, src/renderer/app/components/notifications/notifications.js, src/renderer/common/components/dropdown/dropdown.styles.less, src/renderer/common/components/modal/components/modal-delete-connection/modal-delete-connection.styles.less, src/renderer/common/components/modal/components/modal-download-geth/modal-download-geth.styles.less, src/renderer/common/components/modal/components/modal-edit-connection/modal-edit-connection.styles.less
https://app.clubhouse.io/augur/story/15765/pressing-disconnect-in-app
=> add disconnect message to make delay better

package-lock.json, package.json
bump:
augur-ui 5.7.0
augur-node 5.7.0
augur.js 5.5.0
=> augur.js@5.5.0

src/main/main.js, src/renderer/app/app.styles.less, src/renderer/app/components/connecting-view/connecting-view.styles.less, src/renderer/app/components/processing-view/processing-view.styles.less, src/renderer/common/components/dropdown/dropdown.styles.less
=> fix for window scroll bars

src/renderer/app/components/network-dropdown/network-dropdown.styles.less
give arrow height so that there isn't random hover spot above network dropdown
=> fix network dropdown hover bug

src/renderer/app/components/connecting-view/connecting-view.styles.less
=> alter transitions

package-lock.json, package.json
update 1.7.0-snapshot to augur-node@5.10.1
=> augur-node@5.10.1

src/main/augurNodeServer.js
[CH issue](https://app.clubhouse.io/augur/story/17110/reset-db-doesn-t-work-until-a-connection-is-made)
=> Fix DB renaming when connection has not been established

src/main/configManager.js
merge function params were reversed.
Also just made it always merge in since its quick and reduces code and possible weird failure cases in the future
=> make the merge for config actually merge

package-lock.json, package.json
=> augur-node@6.0.1

package-lock.json, package.json
=> augur.js@5.10.3 augur-ui@5.10.5 augur-node@6.0.3

src/main/check-for-updates.js
=> remove p from promise chain that causes hang

src/main/configManager.js, src/renderer/app/App.js, src/renderer/app/components/network-dropdown/network-dropdown.js, src/renderer/app/components/network-dropdown/network-dropdown.styles.less, src/renderer/common/components/modal/components/modal-download-geth/modal-download-geth.js
Story details: https://app.clubhouse.io/augur/story/18034
=> List "mainnet" first in the Augur App network dropdown

package-lock.json, package.json
augur-ui@6.0.0-0
augur-node@7.0.0-0
augur.js@6.0.0
=> Augur js@6.0.0

README.md
If the instructions aren't that clear I can adjust
=> add instructions for using debian repo

src/main/augurNodeServer.js, src/main/configManager.js, src/main/gethNodeController.js
Also making mainnet the default again
=> Reconnect display issue. Light node tweaks. Retry AN forever

package-lock.json, package.json
updates augur-node@7.7.0 and augur-ui@6.6.0
=> Augur ui@6.6.0 augur node@7.7.0

package-lock.json, package.json
=> 1.15.0 snapshot
